### ISSUE TITLE
Problem with pickle version in Python 2.7

### ISSUE THREAD

**Issue by zsavvas** [Hironsan/HateSonar#1]
Hi,

When trying to use Sonar i get an exception for unsupported pickle version. I attach the traceback below:

```
>>> from hatesonar import Sonar
>>> sonar = Sonar()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/savvas/anaconda2/lib/python2.7/site-packages/hatesonar/api.py", line 21, in __init__
    self.estimator = joblib.load(model_file)
  File "/home/savvas/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 578, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/savvas/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 508, in _unpickle
    obj = unpickler.load()
  File "/home/savvas/anaconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/savvas/anaconda2/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3
```
With Python3 i was able to avoid this issue but it will be nice to be solved for 2.7 version too.
Probably a way to fix is to also include pickle files that were pickled with version 2.

Thanks,
Savvas

**Comment by Hironsan** [comment]
Hi, @zsavvas .

Thanks for great proposal!

I'll cope with the problem asap.

**Comment by Hironsan** [comment]
Complete!
